// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FutilIosApi {
  func sdkInt(completion: @escaping (Result<Int64, Error>) -> Void)
  func isHarmonyOs(completion: @escaping (Result<Bool, Error>) -> Void)
  func osVersion(completion: @escaping (Result<[String: String]?, Error>) -> Void)
  func deviceId(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FutilIosApiSetup {
  /// The codec used by FutilIosApi.
  /// Sets up an instance of `FutilIosApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FutilIosApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let sdkIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.futil_ios.FutilIosApi.sdkInt\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      sdkIntChannel.setMessageHandler { _, reply in
        api.sdkInt { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sdkIntChannel.setMessageHandler(nil)
    }
    let isHarmonyOsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.futil_ios.FutilIosApi.isHarmonyOs\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      isHarmonyOsChannel.setMessageHandler { _, reply in
        api.isHarmonyOs { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isHarmonyOsChannel.setMessageHandler(nil)
    }
    let osVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.futil_ios.FutilIosApi.osVersion\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      osVersionChannel.setMessageHandler { _, reply in
        api.osVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      osVersionChannel.setMessageHandler(nil)
    }
    let deviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.futil_ios.FutilIosApi.deviceId\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      deviceIdChannel.setMessageHandler { _, reply in
        api.deviceId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deviceIdChannel.setMessageHandler(nil)
    }
  }
}
